### PR TITLE
contacts page are responsive now

### LINKED ISSUE #29: Make contacts page responsive.

### PR DESCRIPTION
**Pull request by prashant280920**
i have made the table to fit for mobile also. and also changed the UI of table. Fix #29 @vsvipul @Signior-X

### CODE REVIEW

**Comment by vsvipul** [comment]
@prashant280920 attach image for mobile view.

**Comment by Signior-X** [comment]
Cool! Just one suggestion @prashant280920 from next time, wherever you contribute and do any UI changes. 
Try to always attach a screenshot of that. It will help in easy review of the PR.

**Comment by prashant280920** [comment]
Tables are adjustable for phone also 

I made the table to scroll in x-direction 
And also changed the UI
@vsvipul @Signior-X

**Comment by vsvipul** [comment]
Fix tabs to show text as well.

**Comment by Signior-X** [comment]
@prashant280920 give a screenshot

**Comment by prashant280920** [comment]
Due to quiz I am not able to work on tabs. It will take time for me. For rest of the part you can merge the pr

**Comment by Signior-X** [comment]
Okay no problem, rest of the changes looks good in the Screenshot.
Thanks @prashant280920

**Pull request merged**
