### PR TITLE
Added change

### PR DESCRIPTION
**Pull request by batman14-s**
Line 104 and 105 were missing in senate.html so I firstpasted it and then added rel="noopener noreferrer" in the contacts line. I think I have made the wrong changes. please review it once.

### CODE REVIEW

**Comment by Signior-X** [comment]
Thanks a lot for working on this! The changes are correct.

Sorry :)
I would have merged this PR, but it has some conflicts as I feel your master was not updated with the upstream master. And we merged some changes due to which there are some conflicts coming. We can easily resolve the conflicts, but I have some other plans to do, so not merging this one.
I hope you learned a bit while doing this, hope to see some other PR in future.

A tip: Always try to make a PR from a branch different from `master` i.e, working on a different branch for a different issue.

**Comment by Signior-X** [comment]
I have just created a new issue @batman14-s you can check if you want to try!
https://github.com/KamandPrompt/Gymkhana-IITMandi/issues/73 this one is changing the HTML also.
This time first update/reset the master from upstream. Then create a new branch. Work from there.

**Comment by batman14-s** [comment]
> I have just created a new issue @batman14-s you can check if you want to try!
> Issue #73 this one is changing the HTML also.
> This time first update/reset the master from upstream. Then create a new branch. Work from there.



> I have just created a new issue @batman14-s you can check if you want to try!
> Issue #73 this one is changing the HTML also.
> This time first update/reset the master from upstream. Then create a new branch. Work from there.

I'll surely try :)

**Comment by batman14-s** [comment]
> I have just created a new issue @batman14-s you can check if you want to try!
> Issue #73 this one is changing the HTML also.
> This time first update/reset the master from upstream. Then create a new branch. Work from there.

I'll surely try :)

**Pull request closed without merging**
