### PR TITLE
Add want to contribute or report an issue link

### LINKED ISSUE #54: Add "Want to contribute" with github repo link on contributors page
In the `contributors.html` page, add something, so that if someone wants to contribute can find the Github repo and can contribute or report an issue.

### PR DESCRIPTION
**Pull request by Godwindaniel10**
I added a ( want to contribute ) link, that redirects to the specific Github repo.

and instead of using the phrase( want to contribute ? ),   I used ( want to contribute or Report an issue ? ). so it will be more open and straightforward.

Fixes #54

### CODE REVIEW

**Comment by Signior-X** [comment]
The changes look good to me. Also, thanks for working on this one.
Just one thing, you created your branch from some other branch, so some extra commit, which should not have been in this PR is also comming.

Try to remove `Added an HTML target attribute to the contributors github link` commit from this PR. And have only the changes which are required. Just after that, this PR will be ready to merge :tada:

**Review by Signior-X — CHANGES_REQUESTED** [review]
Remove the unnecessary changes as said in the above comment.

**Comment by Signior-X** [comment]
Thanks for working on this and for your valuable contribution.
Your changes were awesome, but just we merged some PR which closed the issue and we feel the design good for that.

I hope you learned a lot.

**Comment by Godwindaniel10** [comment]
yeah, awesome tho. I learned more than a lot 😊, thank you.

**Pull request closed without merging**
